# Generated by Django 6.0.4 on 2026-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('religion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('religion_name', models.CharField(max_length=100)),
            ],
        ),
    ]
