# Generated by Django 6.0.4 on 2026-06-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_quota'),
    ]

    operations = [
        migrations.CreateModel(
            name='programme',
            fields=[
                ('pgm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pgm_name', models.CharField(max_length=150)),
                ('no_of_sems', models.IntegerField()),
                ('grad_level', models.CharField(max_length=20)),
                ('department', models.ForeignKey(db_column='dept_id', on_delete=django.db.models.deletion.CASCADE, to='students.department')),
            ],
        ),
    ]
