# Generated by Django 6.0.4 on 2026-06-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dep_id', models.IntegerField(primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('stream_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stud_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admn_no', models.CharField(max_length=20)),
                ('roll_no', models.CharField(blank=True, max_length=20, null=True)),
                ('uty_reg_no', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=255)),
                ('year_of_admn', models.IntegerField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(max_length=1)),
                ('caste_id', models.IntegerField(blank=True, null=True)),
                ('religion_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('house_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('place', models.CharField(blank=True, max_length=255, null=True)),
                ('dist', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('pgm_id', models.IntegerField(blank=True, null=True)),
                ('marks_sslc', models.FloatField(blank=True, null=True)),
                ('marks_twelth', models.FloatField(blank=True, null=True)),
                ('board_twelth', models.CharField(blank=True, max_length=100, null=True)),
                ('quota', models.IntegerField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('differently_abled', models.BooleanField(default=False)),
                ('date_of_admission', models.DateField(blank=True, null=True)),
                ('date_of_leaving', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
