# Generated by Django 6.0.4 on 2026-06-17 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_religion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caste',
            fields=[
                ('caste_id', models.IntegerField(primary_key=True, serialize=False)),
                ('caste_name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.CASCADE, to='students.category')),
                ('religion', models.ForeignKey(db_column='religion_id', on_delete=django.db.models.deletion.CASCADE, to='students.religion')),
            ],
        ),
    ]
