# Generated by Django 6.0.4 on 2026-06-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_caste'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('quota_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quota_name', models.CharField(max_length=100)),
            ],
        ),
    ]
