# Generated by Django 6.0.4 on 2026-06-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_foreign_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_studying',
            field=models.BooleanField(default=True),
        ),
    ]
